### ISSUE TITLE
Microlens doesn't build with GHC-8.8.1

### ISSUE THREAD

**Issue by recursion-ninja** [monadfix/microlens#124]
I tried to build with commit 537b9a55f158b375f76f2abda455319772277694

But it fails, due to `MonadFail`.

```
[3 of 4] Compiling Lens.Micro
microlens                        >               
microlens                        > /tmp/stack31990/microlens-0.4.11.1/src/Lens/Micro.hs:1465:5: error:
microlens                        >     ‘fail’ is not a (visible) method of class ‘Monad’
microlens                        >      |        
microlens                        > 1465 |     fail str = StateT $ \ _ -> fail str
microlens                        >      |     ^^^^
microlens                        >               
microlens                        > /tmp/stack31990/microlens-0.4.11.1/src/Lens/Micro.hs:1466:16: error:
microlens                        >     The INLINE pragma for ‘fail’ lacks an accompanying binding
microlens                        >       (The INLINE pragma must be given where ‘fail’ is declared)
microlens                        >      |        
microlens                        > 1466 |     {-# INLINE fail #-}
microlens                        >      |                ^^^^
microlens                        >               
polyparse                        >               
polyparse                        > /tmp/stack31990/polyparse-1.12.1/src/Text/ParserCombinators/HuttonMeijer.hs:66:4: error:
polyparse                        >     ‘fail’ is not a (visible) method of class ‘Monad’
polyparse                        >    |
polyparse                        > 66 |    fail            = Fail.fail
polyparse                        >    |    ^^^^
polyparse                        >    
```

**Comment by neongreen** [comment]
GHC 8.8 is not released yet. The 8.8-compatible branch is at #111.

**Comment by neongreen** [comment]
Actually, whatever, I'll release a patch version now.

**Comment by neongreen** [comment]
By "now" I mean "tomorrow".

**Comment by neongreen** [comment]
By "tomorrow" I mean "now".

Uploaded microlens and microlens-th.
